language: scala

scala:
  - 2.12.6

jdk:
  - openjdk11

script:
  - sbt clean coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 83b35996-c277-426e-a61c-bd0ec51e7664
